//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCjqueryAjax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PatientMaster
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string MRN { get; set; }
        [Display(Name ="Patient Name")]
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public string City { get; set; }
    }
}
